Repository khulnasoft/reconpoint, pull requests merged in 2024-08, with the labels that each got.

#26 Gitworkflows patch 2
  Makefile
  README.md
  certs/entrypoint.sh
  config/nginx/reconpoint.conf
  default_yaml_config.yaml
  docker-compose.dev.yml
  docker-compose.setup.yml
  docker-compose.yml
  install.sh
  make.bat
  web/Dockerfile
  web/api/urls.py
  web/api/views.py
  web/celery-entrypoint.sh
  web/fixtures/default_scan_engines.yaml
  web/reconPoint/common_func.py
  web/reconPoint/context_processors.py
  web/reconPoint/definitions.py
  web/reconPoint/init.py
  web/reconPoint/llm.py
  web/reconPoint/settings.py
  web/reconPoint/tasks.py
  web/reconPoint/urls.py
  web/reconPoint/utilities.py
  web/reconPoint/views.py
  web/recon_note/migrations/0001_initial.py
  web/recon_note/migrations/0002_todonote_project.py
  web/recon_note/static/note/js/todo.js
  web/requirements.txt
  web/scanEngine/templates/scanEngine/add_engine.html
  web/scanEngine/templates/scanEngine/settings/api.html
  web/scanEngine/urls.py
  web/scanEngine/views.py
  web/templates/base/base.html
  web/templates/base/login.html
Labels: documentation, enhancement, dependencies, Configuration changes, Review effort [1-5]: 4

#31 Fix/func
  web/api/views.py
  web/manage.py
  web/reconPoint/common_func.py
  web/reconPoint/tasks.py
  web/reconPoint/urls.py
  web/reconPoint/views.py
  web/templates/base/base.html
  web/templates/base/login.html
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#37 Update Dockerfile
  web/Dockerfile
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#40 Update Dockerfile
  web/Dockerfile
Labels: enhancement, Review effort [1-5]: 2

#44 Update Dockerfile
  web/Dockerfile
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#47 fix/code
  .env
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/SPONSORS.md
  .github/dependabot.yml
  .github/release.yml
  .github/stale.yml
  .github/workflows/add-to-project.yml
  .github/workflows/auto-comment.yml
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dep-auto-merge.yml
  .github/workflows/dockerhub-push.yml
  .github/workflows/github-pages-deploy.yml
  CHANGELOG.md
  CONTRIBUTORS.md
  LICENSE
  README.md
  certs/entrypoint.sh
  docker-compose.dev.yml
  docker-compose.yml
  install.sh
  scripts/uninstall.sh
  update.sh
  web/Dockerfile
  web/api/views.py
  web/celery-entrypoint.sh
  web/dashboard/templates/dashboard/index.html
  web/manage.py
  web/reconPoint/common_func.py
  web/reconPoint/context_processors.py
  web/reconPoint/definitions.py
  web/reconPoint/gpt.py
  web/reconPoint/llm.py
  web/reconPoint/tasks.py
  web/reconPoint/utilities.py
  web/reconPoint/views.py
  web/scanEngine/forms.py
  web/scanEngine/migrations/0001_initial.py
  web/scanEngine/migrations/0002_auto_20220526_1457.py
  web/scanEngine/migrations/0003_enginetype_waf_detection.py
  web/scanEngine/migrations/0004_auto_20220816_0946.py
  web/scanEngine/migrations/0005_notification_send_scan_tracebacks.py
  web/scanEngine/migrations/0006_alter_installedexternaltool_version_lookup_command.py
  web/scanEngine/models.py
  web/scanEngine/templates/scanEngine/_items/form_engine.html
  web/scanEngine/templates/scanEngine/settings/llm_toolkit.html
  web/scanEngine/templates/scanEngine/settings/notification.html
  web/scanEngine/templates/scanEngine/wordlist/add.html
  web/startScan/templates/startScan/detail_scan.html
  web/startScan/templates/startScan/vulnerabilities.html
  web/static/custom/custom.js
  web/targetApp/models.py
  web/targetApp/templates/target/summary.html
  web/templates/base/_items/top_bar.html
  web/templates/base/base.html
  web/templates/base/login.html
Labels: enhancement, github_actions, Bug fix, Review effort [1-5]: 4
